name: Build CMSIS pack
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pack:
    name: Generate pack
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch tags
        if: github.event_name == 'release'
        run: |
          git fetch --tags --force

      - uses: Open-CMSIS-Pack/gen-pack-action@main
        with:
          doxygen-version: none
          packchk-version: 1.4.1
          gen-pack-script: ./gen_pack.sh

      - name: Upload pack
        uses: actions/upload-artifact@v4
        with:
          name: Generated CMSIS pack (in zip archive)
          path: ./output/*.pack
          overwrite: true
          retention-days: 3
